# Generated by Django 3.2.9 on 2022-06-14 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_name', models.CharField(help_text='Name Of Recipe', max_length=200)),
                ('recipe_info', models.TextField(blank=True, help_text='Give Some Information About This recipe', max_length=50, null=True)),
                ('recipe_image', django_resized.forms.ResizedImageField(crop=None, force_format='jpeg', keep_meta=True, quality=100, size=[320, 300], upload_to='recipe_images')),
                ('recipe_details', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='')),
                ('preparation_time', models.IntegerField(help_text='Time to prepare the ingredients, e.g 10 (for 10 minutes)')),
                ('cooking_time', models.IntegerField(help_text='Time to cook the ingredients, e.g 10 (for 10 minutes)')),
                ('category', models.CharField(choices=[('Healthy', 'Healthy'), ('Drinks', 'Drinks'), ('Pastries', 'Pastries'), ('Native', 'Native')], max_length=12)),
                ('serving', models.CharField(choices=[('1 to 3', '1 to 3'), ('3 to 5', '3 to 5'), ('5 to 7', '5 to 7'), ('more Than 7', 'more Than 7')], max_length=15)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Write A Comment On This Recipe')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
