# Generated by Django 3.2.9 on 2022-06-14 11:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_details',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_info',
            field=models.TextField(blank=True, help_text='Give Some Information About This recipe', max_length=1000, null=True),
        ),
    ]
