# Generated by Django 3.2.9 on 2022-06-14 17:53

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(help_text='Write A Comment On This Recipe', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpeg', keep_meta=True, quality=100, size=[500, 500], upload_to='uploads/recipe_images'),
        ),
    ]
