# Generated by Django 3.2.9 on 2022-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220614_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Dessert', 'Dessert'), ('Drinks', 'Drinks'), ('Healthy and Tasty', 'Healthy and Tasty'), ('Native', 'Native'), ('Pastries', 'Pastries'), ('Soup', 'Soup')], max_length=20),
        ),
    ]
