# Generated by Django 3.2.9 on 2022-06-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['recipe']},
        ),
    ]
