# Generated by Django 3.2.9 on 2022-06-19 20:37

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_rename_recipe_details_recipe_recipe_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='youtube_video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=200),
        ),
    ]
