# Generated by Django 3.2.9 on 2022-06-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20220619_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRecipe',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('recipe_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='recipebook',
            name='api_recipes',
            field=models.ManyToManyField(to='recipes.ApiRecipe'),
        ),
    ]
