# Generated by Django 3.2.9 on 2022-07-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_apirecipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirecipe',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apirecipe',
            name='recipe_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirecipe',
            name='time_to_prepare',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
