# Generated by Django 3.2.9 on 2022-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20220703_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirecipe',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
